2025-06-06 10:48:20.325 ERROR (MainThread) [homeassistant.components.mqtt.client] Failed to connect to MQTT server due to exception: [Errno -2] Name does not resolve
2025-06-06 10:48:20.334 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/manual_mqtt/alarm_control_panel.py", line 494, in _async_state_changed_listener
    await mqtt.async_publish(
        self.hass, self._state_topic, new_state.state, self._qos, True
    )
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 182, in async_publish
    await mqtt_data.client.async_publish(
        topic, outgoing_payload, qos or 0, retain or False
    )
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 664, in async_publish
    await self._async_wait_for_mid_or_raise(msg_info.mid, msg_info.rc)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 1279, in _async_wait_for_mid_or_raise
    raise HomeAssistantError(
    ...<5 lines>...
    )
homeassistant.exceptions.HomeAssistantError: <exception str() failed>
2025-06-06 10:53:22.560 ERROR (MainThread) [homeassistant.components.mqtt.util] Error talking to MQTT: The client is not currently connected.
2025-06-06 10:53:32.701 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 1003, in _async_resubscribe_and_publish_birth_message
    await self.async_publish(
    ...<4 lines>...
    )
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 664, in async_publish
    await self._async_wait_for_mid_or_raise(msg_info.mid, msg_info.rc)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 1279, in _async_wait_for_mid_or_raise
    raise HomeAssistantError(
    ...<5 lines>...
    )
homeassistant.exceptions.HomeAssistantError: Error talking to MQTT: The client is not currently connected.
2025-06-06 10:55:10.987 ERROR (MainThread) [homeassistant.components.mqtt.util] Error talking to MQTT: The client is not currently connected.
2025-06-06 10:55:15.993 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 1003, in _async_resubscribe_and_publish_birth_message
    await self.async_publish(
    ...<4 lines>...
    )
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 664, in async_publish
    await self._async_wait_for_mid_or_raise(msg_info.mid, msg_info.rc)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 1279, in _async_wait_for_mid_or_raise
    raise HomeAssistantError(
    ...<5 lines>...
    )
homeassistant.exceptions.HomeAssistantError: Error talking to MQTT: The client is not currently connected.
2025-06-06 11:13:04.269 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:13:11.353 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:13:25.352 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:13:34.666 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:13:39.409 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:13:46.391 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:14:00.360 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:14:05.014 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:14:12.011 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:14:14.371 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:14:21.394 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:14:26.038 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:14:28.453 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:14:37.660 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'test1':
In 'condition':
  In 'state':
    In 'state' condition: unknown entity alarm_control_panel.home_alarm_2
2025-06-06 11:15:42.181 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
